# Generated by Django 5.2.8 on 2025-11-09 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ram', models.IntegerField(verbose_name='RAM')),
                ('cpu', models.IntegerField(verbose_name='CPU')),
                ('ssd', models.IntegerField(verbose_name='SSD')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'db_table': 'tariffs',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершен'), (4, 'Отклонен'), (5, 'Удален')], default=1, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_formation', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('days', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'прогноз',
                'verbose_name_plural': 'прогнозы',
                'db_table': 'forecasts',
                'ordering': ('-date_formation',),
            },
        ),
        migrations.CreateModel(
            name='TariffForecast',
            fields=[
                ('pk', models.CompositePrimaryKey('tariff_id', 'forecast_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.forecast')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.tariff')),
            ],
            options={
                'verbose_name': 'м-м',
                'verbose_name_plural': 'м-м',
                'db_table': 'tariff_forecast',
                'ordering': ('pk',),
            },
        ),
    ]
